version: "3.6"
services:
  zookeeper:
    image: zookeeper:3.5

  mesos-master:
    image: mesosphere/mesos-master:1.5.0
    depends_on:
      - zookeeper
    ports:
      - 5050:5050
    environment:
      MESOS_PORT: 5050
      MESOS_ZK: zk://zookeeper:2181/mesos
      MESOS_QUORUM: 1
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos

  mesos-slave:
    image: mesosphere/mesos-slave:1.5.0
    privileged: true
    depends_on:
      - mesos-master
    environment:
      MESOS_PORT: 5051
      MESOS_MASTER: zk://zookeeper:2181/mesos
      MESOS_SWITCH_USER: 0
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos
      MESOS_SYSTEMD_ENABLE_SUPPORT: "false"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/local/bin/docker:/usr/local/bin/docker
